---
- hosts: clients
  become: true

  tasks:
    - name: Install Apache HTTP server
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache service
      systemd:
        name: httpd
        state: started
        enabled: true

    - name: Copy static website files to the web server document root
      copy:
        src: /root/mine/stat/
        dest: /var/www/html/
        owner: apache
        group: apache
        mode: 0755
        remote_src: no

    - name: Ensure Apache is running
      service:
        name: httpd
        state: started
    - name: Ensure Apache is running
      service:
        name: httpd
        state: started    
    